### ISSUE TITLE
[Build] Enhance Xcodegen architecture

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-x-ios#11]
Actually, the structure uses 3 `xcodegen` files to generate the 3 TchapX targets:
- TchapX-development : TchapX/development/SupportingFiles/target.yml
- TchapX-staging : TchapX/staging/SupportingFiles/target.yml
- TchapX-production : TchapX/staging/SupportingFiles/target.yml

The 3 `target.yml` files are identical except for some properties in `base:settings:`

```
    settings:
      base:
        PRODUCTION_APP_NAME: Tchap DEVELOPMENT
        BASE_APP_GROUP_IDENTIFIER: fr.gouv.tchapx.dev
        BASE_BUNDLE_IDENTIFIER: fr.gouv.tchapx.dev
        APP_NAME: TchapX-development
        APP_DISPLAY_NAME: TchapX-DEVELOPMENT
        ASSETCATALOG_COMPILER_APPICON_NAME: TchapX-icon
```

It should be better if these # files could be on unique template file accepting parameters: 
- either via environment variables
- via a templating phase using Genesis : https://github.com/yonaskolb/Genesis (made by the author of xcodegen)

Xcodegen is not made for templating.

It is possible to use envionment variables in xcodegen: 
```
export TCHAPX_TARGET_BASEDIR="<my custom path>"
xcodegen generate --spec tchapx-project.yml
```

These will replace `${TCHAPX_TARGET_BASEDIR}` string with the value provided.
This means 3 calls, one for each target, or 3 set of variables for each project.

I prefer exploring `Genesis` path.
